language: php

sudo: false

php:
- 5.6

install:
- composer install
  
before_script:
- export PATH="$HOME/.composer/vendor/bin:$PATH"
- composer self-update
- composer init -n
- composer config repositories.repo-name vcs https://github.com/stephenharris/po-test
- composer require po-test/po-test:dev-master 

script: 
- vendor/bin/po-test


